"run_type": "abstract"
"buggy_path": "examples/learning_fix/data/median/raw/buggy/"
"fixed_path": "examples/learning_fix/data/median/raw/fixed/"
"output_dir": "examples/learning_fix/data/median/"
"idioms_path": "examples/learning_fix/data/idioms/idioms.csv"
"nums_worker": 10
"with_position": false
"output_position": false