preprocess:
  work_model: preprocess
  train_src: examples/learning_fix/data/big/train-buggy.txt
  train_tgt: examples/learning_fix/data/big/train-fixed.txt
  valid_src: examples/learning_fix/data/big/eval-buggy.txt
  valid_tgt: examples/learning_fix/data/big/eval-fixed.txt
  save_data: examples/learning_fix/data/big/big
  src_seq_length: 99042
  tgt_seq_length: 99042
  src_seq_length_trunc: 400
  tgt_seq_length_trunc: 200
  num_threads: 10
  overwrite: True
  share_vocab: True
  pos_vec_size: 256
  data_type: "code"

train:
  work_model: train
  data: examples/learning_fix/data/big/big
  save_model: examples/learning_fix/data/big/2/big
#  train_from: examples/learning_fix/data/big/1/big-step-100000-acc-62.30-ppl-3.63-xent-1.29.pt
  save_checkpoint_steps: 5000
  keep_checkpoint: 10
  seed: 3435
  train_steps: 200000
  valid_steps: 5000
  early_stopping: 5
  warmup_steps: 4000
  report_every: 1000

  decoder_type: transformer
  encoder_type: transformer
  word_vec_size: 64
  rnn_size: 64
  layers: 6
  transformer_ff: 256
  heads: 8

  accum_count: 8
  optim: adam
  adam_beta1: 0.9
  adam_beta2: 0.98
  decay_method: noam
  learning_rate: 0.01
  max_grad_norm: 0.0

  batch_size: 1024
  batch_type: tokens
  normalization: tokens
  dropout: 0.1
  label_smoothing: 0.1

  max_generator_batches: 2

  param_init: 0.0
  param_init_glorot: 'true'
  position_encoding: 'true'

  master_port: 8003
  world_size: 4
  gpu_ranks:
    - 0
    - 1
    - 2
    - 3

translate:
  work_model: translate
#  model: examples/learning_fix/data/big/big_step_50000.pt
  src: examples/learning_fix/data/big/test-buggy.txt
  tgt: examples/learning_fix/data/big/test-fixed.txt
  output: examples/learning_fix/data/big/2/predictions.txt
  data_type: "code"
  share_vocab: True
  min_length: 0
  max_length: 100
  batch_size: 1024
#  report_align: 'true'
