train_src: examples/learning_fix/data/small/src-train.txt
train_tgt: examples/learning_fix/data/small/tgt-train.txt
valid_src: examples/learning_fix/data/small/src-val.txt
valid_tgt: examples/learning_fix/data/small/tgt-val.txt
save_data: examples/learning_fix/data/small/small
src_seq_length: 46680
tgt_seq_length: 46680
src_seq_length_trunc: 400
tgt_seq_length_trunc: 100
