model: examples/learning_fix/data/small/small_step_20000.pt
data_type: "code"
src: examples/learning_fix/data/small/test-buggy.txt
tgt: examples/learning_fix/data/small/test-fixed.txt
output: examples/learning_fix/data/small/predictions.txt
share_vocab: True
beam_size: 5
min_length: 0
max_length: 100
batch_size: 4096