train_src: examples/learning_fix/data/small/train-buggy.txt
train_tgt: examples/learning_fix/data/small/train-fixed.txt
valid_src: examples/learning_fix/data/small/eval-buggy.txt
valid_tgt: examples/learning_fix/data/small/eval-fixed.txt
save_data: examples/learning_fix/data/small/small
src_seq_length: 46680
tgt_seq_length: 46680
src_seq_length_trunc: 400
tgt_seq_length_trunc: 200
num_threads: 10
overwrite: True
share_vocab: True
data_type: "code"
