data: examples/learning_fix/data/small_old/small_old
save_model: examples/learning_fix/data/small_old/small_old
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435
train_steps: 50000
valid_steps: 10000
warmup_steps: 4000
report_every: 4000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 128
rnn_size: 128
layers: 6
transformer_ff: 1024
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0

