preprocess:
  work_model: preprocess
  train_src: examples/learning_fix/data/small_old/train-buggy.txt
  train_tgt: examples/learning_fix/data/small_old/train-fixed.txt
  valid_src: examples/learning_fix/data/small_old/eval-buggy.txt
  valid_tgt: examples/learning_fix/data/small_old/eval-fixed.txt
  save_data: examples/learning_fix/data/small_old/small_old
  src_seq_length: 46680
  tgt_seq_length: 46680
  src_seq_length_trunc: 400
  tgt_seq_length_trunc: 200
  num_threads: 10
  overwrite: True
  share_vocab: True
  pos_vec_size: 256
  data_type: "code"

train:
  work_model: train
  data: examples/learning_fix/data/small_old/small_old
  save_model: examples/learning_fix/data/small_old/8/small_old
  train_from: examples/learning_fix/data/small_old/8/small_old-step-33000-acc-99.17-ppl-1.02-xent-0.02.pt
  save_checkpoint_steps: 1000
  keep_checkpoint: 10
  seed: 3435
  train_steps: 50000
  valid_steps: 1000
  early_stopping: 10
  warmup_steps: 4000
  report_every: 1000

  decoder_type: transformer
  encoder_type: transformer
  word_vec_size: 512
  rnn_size: 512
  layers: 6
  transformer_ff: 1024
  heads: 8

  accum_count: 8
  optim: adam
  adam_beta1: 0.9
  adam_beta2: 0.98
  decay_method: noam
  learning_rate: 0.1
  max_grad_norm: 5

  batch_size: 4096
  batch_type: tokens
  normalization: tokens
  dropout: 0.3
#  dropout_steps: 1000
  label_smoothing: 0.0

  max_generator_batches: 2

  param_init: 0.0
  param_init_glorot: 'true'
  position_encoding: 'true'

  master_port: 11111
  world_size: 4
  gpu_ranks:
    - 0
    - 1
    - 2
    - 3

translate:
  work_model: translate
  model: examples/learning_fix/data/small_old/8/small_old-step-33000-acc-99.17-ppl-1.02-xent-0.02.pt
  src: examples/learning_fix/data/small_old/test-buggy.txt
  tgt: examples/learning_fix/data/small_old/test-fixed.txt
  output: examples/learning_fix/data/small_old/8/predictions.txt
  data_type: "code"
  share_vocab: True
  min_length: 0
  max_length: 100
  batch_size: 4096
