preprocess:
  work_model: preprocess
  train_src: examples/learning_fix/data/small/train-buggy.txt
  train_tgt: examples/learning_fix/data/small/train-fixed.txt
  valid_src: examples/learning_fix/data/small/eval-buggy.txt
  valid_tgt: examples/learning_fix/data/small/eval-fixed.txt
  save_data: examples/learning_fix/data/small/small
  src_seq_length: 46680
  tgt_seq_length: 46680
  src_seq_length_trunc: 400
  tgt_seq_length_trunc: 200
  num_threads: 10
  overwrite: True
  share_vocab: True
  pos_vec_size: 256
  data_type: "code"

train:
  work_model: train
  data: examples/learning_fix/data/small/small
#  train_from: examples/learning_fix/data/small/2/small-step-100000-acc-95.04-ppl-1.19-xent-0.18.pt
  save_checkpoint_steps: 5000
  keep_checkpoint: 1000
  seed: 3435
  train_steps: 200000
  valid_steps: 5000
  early_stopping: 10
  warmup_steps: 4000
  report_every: 1000


  decoder_type: transformer
  encoder_type: transformer
  word_vec_size: 512
  rnn_size: 512
  enc_layers: 6
  dec_layers: 4
  transformer_ff: 2048
  heads: 8

  accum_count: 8
  optim: adam
  adam_beta1: 0.9
  adam_beta2: 0.98
  decay_method: noam
  learning_rate: 0.01
  max_grad_norm: 5

  batch_size: 4096
  batch_type: tokens
  normalization: tokens
  dropout: 0.2
  label_smoothing: 0.1

  max_generator_batches: 2

  param_init: 0.0
  param_init_glorot: 'true'
  position_encoding: 'true'


  sampling_type: "scheduled"
  mixture_type: "all_teacher_suggesting"
  transformer_scheduled_activation: "gumbel"
  scheduled_sampling_decay: "sigmoid"
  scheduled_sampling_k: 10000
  transformer_scheduled_alpha: 0.5
  external_evaluators: 'bleu'

  master_port: 8003
  world_size: 2
  gpu_ranks:
    - 0
    - 1

translate:
  work_model: translate
#  model: examples/learning_fix/data/small/10/small-step-132000-acc-95.46-ppl-1.17-xent-0.16.pt
  src: examples/learning_fix/data/small/test-buggy.txt
  tgt: examples/learning_fix/data/small/test-fixed.txt
  data_type: "code"
  share_vocab: True
  min_length: 0
  max_length: 100
  batch_size: 16
  gpu: 0
#  report_align: 'true'
